# .github/workflows/perf-guard.yml
name: perf-guard
on: [push]

jobs:
  latency:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24.0.1'

      - name: Build with Maven
        run: mvn -q package -DskipTests

      - name: Start server (virtual threads mode)
        run: |
          java -Dvt=true -jar target/*jar &
          echo $! > pid.txt
          sleep 6

      - name: Install ApacheBench
        run: sudo apt-get update && sudo apt-get install -y apache2-utils
