name: perf-guard
on: [push]

jobs:
  latency:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 25
    - run: mvn -q package -DskipTests
    - run: |
        java -Dvt=true -jar target/*jar &
        echo $! > pid.txt
        sleep 6
    - run: sudo apt-get update && sudo apt-get install -y apache2-utils
    - run: |
        ab -n 3000 -c 200 http://127.0.0.1:8080/io > ab.out
        LAT=$(grep "95%" ab.out | awk '{print $2}')
        echo "p95 latency = $LAT ms"
        if [ "$LAT" -gt 150 ]; then exit 1; fi   # threshold 150 ms
    - run: kill $(cat pid.txt)
